package main

import (
	"flag"
	"github.com/Wastack/adventure/controller"
	"github.com/Wastack/adventure/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/Wastack/adventure/engine"
	"github.com/Wastack/adventure/engine/data/yaml"
	"github.com/gin-gonic/gin"
	"github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"
	"io/ioutil"
	"log"
	"os"
)

func parse(file_path string, is_verbose bool) (engine.GameDataI, error) {
	file, err := os.Open(file_path)
	if err != nil {
		return nil, err
	}
	b, err := ioutil.ReadAll(file)
	if err != nil {
		return nil, err
	}
	return yaml.Parse_yaml(b, is_verbose)
}

type CmdParams struct {
	port_number string
	with_api    bool
	yaml_path   string
	is_verbose  bool
}

func parse_clo() (params CmdParams) {
	portPtr := flag.String("port", "8080", "API port")
	withApiPtr := flag.Bool("with-api", true, "whether API should be served")
	isVerbosePtr := flag.Bool("verbose", false, "Verbose output")
	flag.Parse()
	params = CmdParams{
		port_number: *portPtr,
		with_api:    *withApiPtr,
		is_verbose:  *isVerbosePtr,
	}
	args := flag.Args()
	if len(args) < 1 {
		log.Fatalf("Missing yaml file path as first argument\n")
	}
	params.yaml_path = args[0]
	return
}

func main() {
	params := parse_clo()
	game_data, err := parse(params.yaml_path, params.is_verbose)
	if err != nil {
		log.Fatalf("Error while parsing yaml file: %v", err)
	}

	if params.with_api {
		if !params.is_verbose {
			gin.SetMode(gin.ReleaseMode)
		}
		// Set swagger info
		docs.SwaggerInfo.Title = "Swagger Adventure API"
		docs.SwaggerInfo.Description = "This is a server for the adventure game engine."
		docs.SwaggerInfo.Version = "0.0"
		r := gin.New()

		c := controller.NewController(game_data)

		// Create API for engine
		adventure := r.Group("/adventure")
		{
			adventure.GET("/first", c.ShowFirstState)
			adventure.GET("", c.NextState)
			adventure.GET("/secret", c.ResolveSecret)
		}

		// use ginSwagger middleware to serve the API docs
		r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))
		r.Run(":" + params.port_number)
	}
}
